# Generated by Django 4.0.4 on 2022-05-29 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_people', '0003_userprofile_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='country',
        ),
    ]
