# Generated by Django 4.0.4 on 2022-05-01 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InternetLocation',
            fields=[
                ('location_type', models.CharField(choices=[('HN_N', 'HackerNews_News'), ('IH_P', 'IndieHacker_PopularPosts')], max_length=128, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='InternetContent',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('title', models.CharField(max_length=512)),
                ('url', models.URLField()),
                ('additional_fields', models.JSONField()),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='the_news.internetlocation')),
            ],
        ),
    ]
