# Generated by Django 4.0.4 on 2022-05-02 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internetnews',
            name='description',
            field=models.TextField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='internetnews',
            name='image_src',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='internetlocation',
            name='location_type',
            field=models.CharField(choices=[('HN_N', 'Hacker News'), ('IH_P', 'Indie Hackers')], max_length=128, primary_key=True, serialize=False),
        ),
    ]
