# Generated by Django 4.0.4 on 2022-05-02 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_news', '0002_internetnews_description_internetnews_image_src_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internetnews',
            name='comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='internetnews',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='internetlocation',
            name='location_type',
            field=models.CharField(choices=[('HN_N', 'Hacker News'), ('IH_P', 'Indie Hackers'), ('PH_T', 'Product Hunt')], max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='internetnews',
            name='description',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='internetnews',
            name='image_src',
            field=models.URLField(blank=True, null=True),
        ),
    ]
