# Generated by Django 4.0.4 on 2022-05-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_news', '0003_internetnews_comments_internetnews_upvotes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internetlocation',
            name='location_type',
            field=models.CharField(choices=[('HN_N', 'Hacker News'), ('IH_P', 'Indie Hackers'), ('PH_T', 'Product Hunt'), ('R_C_T', 'Reddit')], max_length=128, primary_key=True, serialize=False),
        ),
    ]
