# Generated by Django 4.0.4 on 2022-05-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_news', '0004_alter_internetlocation_location_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internetlocation',
            name='location_type',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
    ]
