# Generated by Django 4.0.4 on 2022-05-08 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('the_news', '0005_alter_internetlocation_location_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternetLocationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=128, verbose_name='Category Name')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='the_news.internetlocation')),
            ],
        ),
        migrations.AddField(
            model_name='internetnews',
            name='sub_category',
            field=models.ManyToManyField(blank=True, to='the_news.internetlocationcategory'),
        ),
    ]
