# Generated by Django 4.0.4 on 2022-05-12 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('the_news', '0006_internetlocationcategory_internetnews_sub_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNewsProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_internet_location_categories', models.ManyToManyField(blank=True, to='the_news.internetlocationcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
